paths:
  /resource-usage/containers:
    get:
      tags:
      - usage
      summary: Retrieve containers that were running for a user and product taken
        from context.
      operationId: list_resource_usage_containers
      parameters:
      - required: false
        schema:
          title: Limit
          type: integer
          default: 20
        name: limit
        in: query
      - required: false
        schema:
          title: Offset
          minimum: 0
          type: integer
          default: 0
        name: offset
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_list_models_library.api_schemas_webserver.resource_usage.ContainerGet__'
components:
  schemas:
    ContainerGet:
      title: ContainerGet
      required:
      - project_uuid
      - node_uuid
      - service_key
      - service_version
      - start_time
      - duration
      - processors
      - core_hours
      - status
      type: object
      properties:
        project_uuid:
          title: Project Uuid
          type: string
          format: uuid
        project_name:
          title: Project Name
          type: string
        node_uuid:
          title: Node Uuid
          type: string
          format: uuid
        node_label:
          title: Node Label
          type: string
        service_key:
          title: Service Key
          pattern: ^simcore/services/((comp|dynamic|frontend))/([a-z0-9][a-z0-9_.-]*/)*([a-z0-9-_]+[a-z0-9])$
          type: string
        service_version:
          title: Service Version
          pattern: ^(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}(-(0|[1-9]\d*|\d*[-a-zA-Z][-\da-zA-Z]*)(\.(0|[1-9]\d*|\d*[-a-zA-Z][-\da-zA-Z]*))*)?(\+[-\da-zA-Z]+(\.[-\da-zA-Z-]+)*)?$
          type: string
        start_time:
          title: Start Time
          type: string
          format: date-time
        duration:
          title: Duration
          type: number
        processors:
          title: Processors
          type: number
        core_hours:
          title: Core Hours
          type: number
        status:
          $ref: '#/components/schemas/ContainerStatus'
    ContainerStatus:
      title: ContainerStatus
      enum:
      - running
      - finished
      type: string
      description: An enumeration.
    Envelope_list_models_library.api_schemas_webserver.resource_usage.ContainerGet__:
      title: Envelope[list[models_library.api_schemas_webserver.resource_usage.ContainerGet]]
      type: object
      properties:
        data:
          title: Data
          type: array
          items:
            $ref: '#/components/schemas/ContainerGet'
        error:
          title: Error
